In [1]:
import sys, os
sys.path.append("../src")

from data_loader import load_data

FILENAME = "ret_sample.csv"
df = load_data(filename=FILENAME)
print(df.shape)
df.head()

Loading data from: /Users/kevin/Coding Projects/Asset-Management-Hackathon-2025/data/ret_sample.csv

/Users/kevin/Coding Projects/Asset-Management-Hackathon-2025/notebooks/../src/data_loader.py:63: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(data_path, **read_kwargs)

(6401414, 159)

,id,date,ret_eom,gvkey,iid,excntry,stock_ret,year,month,char_date,...,betadown_252d,prc_highprc_252d,corr_1260d,betabab_1260d,rmax5_rvol_21d,age,qmj,qmj_prof,qmj_growth,qmj_safety
0,comp_001081_01C,20050228,20050228,1081.0,01C,CAN,-0.143457,2005,2,20050131,...,0.779315,0.672204,0.387781,0.845865,0.805580,541,-1.508294,-0.994164,-0.832048,-1.017248
1,comp_001096_01C,20050228,20050228,1096.0,01C,CAN,0.028077,2005,2,20050131,...,0.445162,0.937664,0.245148,0.456872,0.923214,517,-0.706080,-0.247574,-0.155802,-0.485635
2,comp_001117_02,20050228,20050228,1117.0,02,USA,-0.168627,2005,2,20050131,...,1.073565,0.708333,0.124188,0.863334,0.898113,373,1.344458,1.601108,1.612067,-0.566631
3,comp_001166_01W,20050228,20050228,1166.0,01W,NLD,0.086271,2005,2,20050131,...,1.781000,0.676545,0.560895,1.560202,1.342814,289,-1.355529,-0.904719,-0.999531,-1.231687
4,comp_001186_01C,20050228,20050228,1186.0,01C,CAN,0.149056,2005,2,20050131,...,1.326215,0.774557,0.174888,0.399060,0.777183,385,1.123762,0.154734,1.196690,0.939661

In [14]:
df_sorted = df.sort_values(['gvkey', 'date'])

In [16]:
df_sorted.head(100)

,id,date,ret_eom,gvkey,iid,excntry,stock_ret,year,month,char_date,...,betadown_252d,prc_highprc_252d,corr_1260d,betabab_1260d,rmax5_rvol_21d,age,qmj,qmj_prof,qmj_growth,qmj_safety
18418,crsp_54594,20050228,20050228,1004.0,01,USA,-0.042918,2005,2,20050131,...,2.485557,0.801789,0.442469,1.616144,1.055066,469,-1.422978,-1.170041,-0.826064,-1.138539
40928,crsp_54594,20050331,20050331,1004.0,01,USA,0.219731,2005,3,20050228,...,2.619073,0.767378,0.452369,1.661742,0.938883,470,-1.432880,-1.171511,-0.831722,-1.149303
63578,crsp_54594,20050429,20050430,1004.0,01,USA,0.083088,2005,4,20050331,...,2.456339,0.909091,0.473352,1.837590,2.056687,471,-1.520223,-1.267460,-1.057318,-1.126403
86182,crsp_54594,20050531,20050531,1004.0,1.0,USA,0.088934,2005,5,20050429,...,2.325835,0.984626,0.479609,1.804244,1.332348,472,-1.544141,-1.322609,-1.081592,-1.194552
108819,crsp_54594,20050630,20050630,1004.0,01,USA,-0.020574,2005,6,20050531,...,2.331795,1.000000,0.484271,1.866898,1.466940,473,-1.545540,-1.322095,-1.080716,-1.207021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2343321,crsp_54594,20130131,20130131,1004.0,01,USA,0.013116,2013,1,20121231,...,0.839818,0.799315,0.684232,2.128902,1.843316,564,-0.641085,-0.162034,-0.174399,-0.655112
2367905,crsp_54594,20130228,20130228,1004.0,01,USA,-0.067905,2013,2,20130131,...,0.781344,0.806590,0.682151,2.130870,0.923561,565,-0.653706,-0.160069,-0.202908,-0.655540
2392465,crsp_54594,20130328,20130331,1004.0,01,USA,0.046670,2013,3,20130228,...,0.912467,0.774691,0.680180,2.074676,0.492071,566,-0.658332,-0.162452,-0.201430,-0.652529
2416974,crsp_54594,20130430,20130430,1004.0,01,USA,-0.024742,2013,4,20130328,...,1.047959,0.914470,0.675637,2.099136,1.264985,567,-0.609658,-0.166442,-0.114434,-0.617676
2441444,crsp_54594,20130531,20130531,1004.0,01,USA,0.123180,2013,5,20130430,...,1.229127,0.888115,0.685229,2.137400,1.130583,568,-0.632851,-0.183139,-0.114845,-0.622675

In [3]:
none_values = df['inv_gr1'].isnull()
print(f"Number of None values: {none_values.sum()}")

Number of None values: 2003011

In [4]:
df['inv_gr1'].head()

0    0.024745
1    0.062489
2   -0.229326
3   -0.058613
4    0.268799
Name: inv_gr1, dtype: float64

In [2]:
# ARIMA imports and setup (works with existing df)
import subprocess, sys
import matplotlib.pyplot as plt
import pandas as pd

try:
    import statsmodels.api as sm
    from statsmodels.tsa.arima.model import ARIMA
except Exception:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "statsmodels==0.14.2"])
    import statsmodels.api as sm
    from statsmodels.tsa.arima.model import ARIMA

pd.set_option("display.width", 140)

# Column configuration based on provided schema
DATE_COL = 'date'
ID_COL = 'gvkey'
PRICE_COL = 'prc' if 'prc' in df.columns else None
RET_COL = 'stock_ret' if 'stock_ret' in df.columns else None

print({'DATE_COL': DATE_COL, 'ID_COL': ID_COL, 'PRICE_COL': PRICE_COL, 'RET_COL': RET_COL})

{'DATE_COL': 'date', 'ID_COL': 'gvkey', 'PRICE_COL': 'prc', 'RET_COL': 'stock_ret'}

In [3]:
# Prepare columns based on provided schema

DATE_COL = 'date'  # provided
ID_COL = 'gvkey'   # provided

# Explicit targets per your columns
PRICE_COL = 'prc' if 'prc' in df.columns else None
RET_COLS = [c for c in ['ret_eom', 'stock_ret'] if c in df.columns]

print('Using columns:')
print(f"  DATE_COL={DATE_COL}, ID_COL={ID_COL}")
print(f"  PRICE_COL={PRICE_COL}")
print(f"  RET_COLS={RET_COLS}")

Using columns:
  DATE_COL=date, ID_COL=gvkey
  PRICE_COL=prc
  RET_COLS=['ret_eom', 'stock_ret']

In [ ]:
# Build monthly series for one company (robust, using date/gvkey/prc/stock_ret/ret_eom)

FORCE_ID = None  # e.g., '1003'
min_points_levels = [36, 24, 12, 6, 2]

work_df = df.copy()
work_df[DATE_COL] = pd.to_datetime(work_df[DATE_COL], errors='coerce')
work_df = work_df.dropna(subset=[DATE_COL, ID_COL])

ids_to_try = [FORCE_ID] if FORCE_ID is not None else work_df[ID_COL].astype(str).unique().tolist()

ret_priority = [c for c in ['stock_ret', 'ret_eom'] if c in work_df.columns]

chosen_id, monthly = None, None

for min_pts in min_points_levels:
    best_id, best_series = None, None
    for cid in ids_to_try[:5000]:
        sub = work_df[work_df[ID_COL].astype(str) == str(cid)]
        # Prefer price if available and non-empty; else try returns in priority order
        if PRICE_COL is not None and sub[PRICE_COL].notna().any():
            ts = sub[[DATE_COL, PRICE_COL]].dropna().rename(columns={PRICE_COL: 'price'})
        else:
            ts = None
            for rcol in ret_priority:
                tmp = sub[[DATE_COL, rcol]].dropna().rename(columns={rcol: 'ret'})
                if not tmp.empty:
                    tmp = tmp.sort_values(DATE_COL)
                    tmp['price'] = 100 * (1 + tmp['ret']).cumprod()
                    ts = tmp[[DATE_COL, 'price']]
                    break
            if ts is None:
                continue
        m = ts.set_index(DATE_COL).resample('ME').last().dropna()
        if len(m) >= min_pts and m['price'].std(skipna=True) > 0:
            if best_series is None or len(m) > len(best_series):
                best_id, best_series = cid, m
    if best_id is not None:
        chosen_id, monthly = best_id, best_series
        break

if chosen_id is None:
    raise ValueError("No suitable series found. Ensure 'prc' or 'stock_ret'/'ret_eom' has data.")

print(f"Chosen {ID_COL}: {chosen_id} with {len(monthly)} monthly points. Std={monthly['price'].std():.6f}")
print(monthly.head(), monthly.tail(), sep='\n\n')

In [ ]:
# Fit ARIMA with short-series fallback, forecast one month, plot

series = monthly['price'].asfreq('M')

# Choose order depending on length
n = len(series.dropna())
order = (1,1,1) if n >= 24 else (1,1,0) if n >= 12 else (0,1,1) if n >= 6 else (0,1,0)
print({'n_obs': n, 'order': order})

results = ARIMA(series, order=order).fit()
print(results.summary())

forecast_res = results.get_forecast(steps=1)
forecast_mean = forecast_res.predicted_mean
forecast_ci = forecast_res.conf_int(alpha=0.05)

next_date = forecast_mean.index[-1]
print(f"Next month forecast date: {next_date.date()}  value: {forecast_mean.iloc[-1]:.4f}")
print(f"95% CI: [{forecast_ci.iloc[-1,0]:.4f}, {forecast_ci.iloc[-1,1]:.4f}]")

fig, ax = plt.subplots(figsize=(9,4))
series.plot(ax=ax, label='History')
forecast_mean.plot(ax=ax, style='r--', label='Forecast')
ax.fill_between(forecast_ci.index, forecast_ci.iloc[:,0], forecast_ci.iloc[:,1], color='r', alpha=0.2, label='95% CI')
ax.set_title(f"ARIMA{order} forecast for {ID_COL}={chosen_id}")
ax.set_xlabel('Date')
ax.set_ylabel('Price (level)')
ax.legend()
plt.tight_layout()
plt.show()